baseURL: https://shivant-maharaj.netlify.app/
languageCode: "en-us"
title: "Shivant Maharaj"
theme: "hugo-profile"

Paginate: 3
#disqusShortname: gurusabarish
#googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Shivant Maharaj"
  description: "This website is an online portfolio hosting projects that I have worked on, and providing content on my passions and interests."
  # staticPath: ""  # The path to serve the static files from
  favicon: "/smile.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Shivant."
    subtitle: "I find cool ways to make data useful."
    content: "A passionate data scientist that is interested in finding new technologies to make financial services more inclusive. I enjoy delving into a data set and making intriguing visualisations."
    image: "/images/wave.PNG"
    button:
      enable: true
      name: "My CV"
      #email: "smaharaj.mam2023@london.edu"
      url: "/Shivant Maharaj - CV - August 2022 Pass.pdf"
      download: true 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/shivant-maharaj
        - icon: fab fa-instagram
          url: https://www.instagram.com/shivantmaharaj/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/shivant-maharaj-02b7a8130/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/peace.PNG"
    content: |-
      I am an ambitious South African that is passionate about the use of emerging technology for socio-economic development in Africa. I have a background in business, information systems, and analytics. I have a strong interest in human-computer interaction, Web3, and fintech. I am currently reading for my Masters in Analytics and Management at [London Business School](https://www.london.edu/masters-degrees/masters-in-analytics-and-management) in London, United Kingdom. 

      I am currently keeping an eye out for interesting opportunities in FinTech and Financial Services around  the world. Know of any? Reach out below! 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Amazon Web Services"
        - "R Studio"
        - "PowerBI & Tableau"
        - "Python"
        - "SAS"
        - "SQL"

  # Experience
  experience:
    enable: true
    title: "Experience"
    items:
      - job: "Data Scientist"
        company: "BDO South Africa"
        companyUrl: "https://www.bdo.co.za/en-za/home"
        date: "Jan 2021 - Aug 2022"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content: "I worked as a Data Scientist in Financial Services Technology at [BDO South Africa](https://www.bdo.co.za/en-za/home) after being promoted from a Junior Analyst in October 2020. \n\nI was based in Cape Town and have experience across IFRS 9 & Credit Risk Solutions, Asset Funding, and Insurance to name a few."

      - job: "Head Information Systems Tutor"
        company: "University of Cape Town"
        companyUrl: "https://www.uct.ac.za"
        date: "January 2020 - Dec 2020"
        # featuredLink:
        #   enable: true
        #   url: "https://www.uct.ac.za"
        # info:
        #   enable: true
        #   content: I worked as a software developer for more than one year in Amazon.
        content: |
         I was elected Head Tutor for INF3003W, a final-year software development capstone course. Within the role, I was responsible for: 
         
          - Collaborating with the academic heads to ensure learning outcomes were met;
          - Managing scheudling and deliverable marking on behalf of the tutoring team; and,
          - Orchestrating weekly coding workshops.

      - job: "Volunteer Coding & Robotics Teacher"
        company: "Africa Youth Ignited 4IR"
        companyUrl: "https://www.africanyouthignited.org"
        date: "Jan 2020 - Dec 2020"
        info:
          enable: false
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        content: "Africa Youth Ignited 4IR is a Non-Profit Organisation geared towards equipping the youth of South Africa with the required skills to thrive within the 4th Industrial Revolution. \n\nThe company emphasizes the importance of understanding programming and coding fundamentals to children. Through partnering with schools and industry partners, the company provides students with access to coding and robotics lessons. \n\nI have been moved by this initiative and have joined the company as a volunteer teacher to help transfer my skills onto the next generation of leaders. The employment contract between the organisation and I is voluntary, as I use this platform use my skills to help my community."

      # - job: "UI/UX Designer"
      #   company: "Netflix"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
      # 
      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.
      # 
      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Masters in Analytics and Management"
        school:
          name: "London Business School"
          url: "https://www.london.edu/masters-degrees/masters-in-analytics-and-management"
        date: "2022 - 2023"
        #GPA: "3.8 out of 5.0"
        content: |-
          Courses
            - Applied Statistics
            - Using Data Science Responsibly
      - title: "Bachelor of Business Science specialising in Information Systems"
        school:
          name: "University of Cape Town"
          url: "https://commerce.uct.ac.za/applying-commerce/undergraduate-studies"
        date: "2016 - 2020"
        #GPA: "3.9 out of 5.0"
        content: |-
        
          **Projects**
          - [The Warehouse Trust & RESPOND](http://www.sit.uct.ac.za/sit/news/2019/shield) - Awarded 1st Place Out of 10 Projects
          - City of Cape Town - Business Process Analysis and Redesign - Awarded 3rd Place Out of 16 Projects
          - [Hubble Studios SkyLab](https://showcase.sit.uct.ac.za/event/showcase-2020/hubble-skylab) 
            
          **Roles**
          - Student Representative (2017; 2018; 2019; 2020)
          - Head Tutor [INF3003W] (2020)
          - Honours Outreach and Communitity Involvement Program Representative (2020)

          **Scholarships**
          - Commerce Faculty Scholarship (2019) 
            
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: ViaData Award for Excellence
        content: Awarded for Excellence in Final Year Information Systems courses.
      - title: 1st Place - 3rd Year IS Systems Development Project
        content: Recieved for placing 1st for Systems Development I capstone project. The system was developed using Microsoft ASP.Net MVC and Azure Deployment.
        url: "http://www.sit.uct.ac.za/sit/news/2019/shield"
      - title: 2019 IS Top Achievers Award 
        content: The EY Academic Achievement Award for outstanding achievement in Information Systems. Awarded for placing 3rd out of 16 for a Business Process Redesign for the City of Cape Town. 
      - title: 3rd in Business Science 5 year programme (2016 Cohort)
      - title: Class Medal for Mathematics 1010


  # projects
  projects:
    enable: true
    title: "Academic Projects"
    items:
      - title: Subject Identification with Computer Vision using Python
        content: An image subject identification and extraction exercise using Python and Computer Vision (OpenCV).
        image: /images/projects/computer-vision.jpg
        featured:
          name: View Project
          link: /blogs/DataChallengeV1.html
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-python
          - icon: fa fa-envelope
            url: smaharaj.mam2023@london.edu
          - icon: fab fa-github
            url: https://github.com/shivant-maharaj/subject-extraction-opencv
       
      - title: Omega Plc. Salary Analysis in R
        content: The following assessment was given as a classroom exercise to test our understanding of R, Version Control, and Visualisations using GGPlot2. Salary data from Omega Plc was provided for analysis.
        image: /images/projects/salary.png
        featured:
          name: View Project
          link: /blogs/Omega
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-r-project
          - icon: fab fa-github


      - title: Weather Analysis in R
        content: The following assessment was given as a classroom exercise to test our understanding of R, Version Control, and Visualisations using GGPlot2. Weather data from NASA was provided for analysis.git 
        image: /images/projects/earth.jpeg
        featured:
          name: View Project
          link: /blogs/weather
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-r-project
          - icon: fab fa-github


  #Contact
  contact:
    enable: true
    title: "Let's grab a coffee!"
    content: What to find out more, have a chat, or discuss an idea? Reach out via the email below and I will get back to you!
    email: smaharaj.mam2023@london.edu
    btnName: Email Me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/shivant-maharaj
      linkedin: https://www.linkedin.com/in/shivant-maharaj-02b7a8130/
      instagram: https://www.instagram.com/shivantmaharaj/
